---
title: "Client Report - Project 0: Introduction"
subtitle: "Course DS 250"
author: "Austin Taylor"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
#| label: libraries
#| include: false
import pandas as pd
import numpy as np
import plotly.express as px
```


## Elevator pitch

_paste your elevator pitch here_
_A SHORT (4-5 SENTENCES) PARAGRAPH THAT `DESCRIBES KEY INSIGHTS` TAKEN FROM METRICS IN THE PROJECT RESULTS THINK TOP OR MOST IMPORTANT RESULTS._

```{python}
#| label: project data
#| code-summary: Read and format project data
# Include and execute your code here
df = pd.read_csv("https://github.com/byuidatascience/data4python4ds/raw/master/data-raw/mpg/mpg.csv")
```

__Highlight the Questions and Tasks__

## QUESTION|TASK 1

__Finish the readings and be prepared with any questions to get your environment working smoothly (class for on-campus and Slack for online).__

_Yes, it is working for me._


## QUESTION|TASK 2

__In VS Code, write a python script to create the example chart from section 3.2.2 of the textbook (part of the assigned readings). Note that you will be using Plotly Express to display the chart instead of Altair which is used in the book.__

_type your results and analysis here_

```{python}
#| label: Q2
#| code-summary: Read and format data
# Include and execute your code here


```

_include figures in chunks and discuss your findings in the figure._

```{python}
#| label: Q2 chart
#| code-summary: plot example
#| fig-cap: "My useless chart"
#| fig-align: center
# Include and execute your code here
chart = px.scatter(
    df,
    x="displ", 
    y="hwy",
    color="manufacturer",
    symbol="manufacturer",
    hover_data=["manufacturer", "model","year", "hwy"],
    title="The Relationship Between MPG and Displacement"
)
chart.update_layout(
    xaxis_title = "Engine Displacement (in litres)",
    yaxis_title = "Highway Miles Per Gallon",
    legend_title = "Manufacturer"
)
chart.show()

```


## QUESTION|TASK 3

__Your final report should also include the markdown table created from the following (assuming you have `mpg` from question 2).__

_type your results and analysis here_

```{python}
#| label: Q3
#| code-summary: Read and format data
# Include and execute your code here


```

_include figures in chunks and discuss your findings in the figure._

```{python}
#| label: Q3 table
#| code-summary: table example
#| tbl-cap: "Not much of a table"
#| tbl-cap-location: top
# Include and execute your code here
print(df
  .head(5)
  .filter(["manufacturer", "model","year", "hwy"])
  .to_markdown(index=False))

```